//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alquiler_Video_Juegos.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDAlquiler_Video_JuegosEntities : DbContext
    {
        public BDAlquiler_Video_JuegosEntities()
            : base("name=BDAlquiler_Video_JuegosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Hitorial> Hitorials { get; set; }
        public virtual DbSet<Juego> Juegos { get; set; }
    
        public virtual ObjectResult<SP_HISTORIAL_POR_ID_Result> SP_HISTORIAL_POR_ID(Nullable<int> iDCLIENTE)
        {
            var iDCLIENTEParameter = iDCLIENTE.HasValue ?
                new ObjectParameter("IDCLIENTE", iDCLIENTE) :
                new ObjectParameter("IDCLIENTE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HISTORIAL_POR_ID_Result>("SP_HISTORIAL_POR_ID", iDCLIENTEParameter);
        }
    }
}
