//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alquiler_Video_Juegos.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hitorial
    {
        public int id_Historial { get; set; }
        public int id_Juego { get; set; }
        public int id_Cliente { get; set; }
        public Nullable<System.DateTime> Fecha_Prestamo { get; set; }
        public Nullable<System.DateTime> Fecha_Entrega { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Juego Juego { get; set; }
    }
}
